extends: phase6_daeac_cbam_latefusion_rr_nsv_hybrid_mkmmd_mcc_ds1_ds2.yaml

logging:
  wandb:
    group: phase6_daeac_cbam_latefusion_rr_nsv_hybrid_mkmmd_mcc_ds1_svdb
    tags: ["phase6", "daeac", "cbam", "rr_late_fusion", "nsv", "hybrid_mkmmd_mcc", "ds1_svdb"]

paths:
  output_dir: outputs/phase6_daeac_cbam_latefusion_rr_nsv_hybrid_mkmmd_mcc_ds1_svdb

data:
  target_unlabeled: data/processed/phase6_daeac_record_splits_nsv/svdb_train.npz
  target_val: data/processed/phase6_daeac_record_splits_nsv/svdb_val.npz
  target_test: data/processed/phase6_daeac_record_splits_nsv/svdb_test.npz

adaptation:
  checkpoint_prefix: daeac_cbam_rr_nsv_hybrid_mkmmd_mcc_ds1_svdb
